name: imot
description: Inter Express Mobile Operation Transport - Mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  #sdk: '>=2.12.0 <3.0.0'
  #sdk: '>=2.15.0 <3.0.0'
  sdk: '>=2.17.0 <3.0.0'
  # sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  logger: ^1.1.0
  jwt_decoder: ^2.0.1
  #get:
  #  git:
  #    url: https://github.com/arjundevlucid/getx.git
  #path: packages/getx
  # font_awesome_flutter: ^9.1.0
  #provider: ^6.0.3
  # flutter_hooks: ^0.17.0
  package_info_plus: ^1.4.3+1
  uuid: ^3.0.6

  intl: ^0.17.0
  #android_intent_plus: ^3.1.1
  device_apps: ^2.2.0
  #app_installer: ^1.1.0
  flutter_svg: ^1.1.5
  #device_info_plus: 3.2.4
  #battery: ^2.0.3
  battery_plus: ^2.1.4+1
  dropdown_search: ^5.0.2
  #flutter_share: ^2.0.0
  dio: ^4.0.6
  # rflutter_alert: ^2.0.4

  #workmanager: ^0.5.0
  cron: ^0.5.0
  #flutter_background_service: ^2.1.3

  #share: ^2.0.4
  flutter_dotenv: ^5.0.2

  share_plus: 4.1.0
  #shared_preferences: ^2.0.15

  #infinite_scroll_pagination: ^3.2.0
  # flutter_local_notifications: ^8.2.0
  google_maps_flutter: ^2.2.0
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.0.0
  #location: ^4.4.0
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  flutter_screenutil: ^5.5.4
  flutter_keyboard_visibility: ^5.3.0
  flutter_rounded_date_picker: ^3.0.2
  #location:
  #  git:
  #    url: https://github.com/Yczar/flutterlocation.git
  #    path: packages/location
  image_picker: ^0.8.5+3
  #image_picker:
  #  git:
  #    url: https://github.com/flutter/plugins.git
  #    path: packages/image_picker
  #    ref: main
  flutter_easyloading: ^3.0.5
  qr_code_scanner: ^1.0.1
  #qr_code_scanner:
  #  git:
  #    url: https://github.com/OOTPAppsDotCom/qr_code_scanner.git

  #barcode_scan2: ^4.2.1
  google_fonts: ^3.0.1
  barcode: ^2.2.3

  #qr_code_scanner:
  #      git:
  #          url: https://github.com/X-SLAYER/qr_code_scanner.git
  #          ref: flutter-beta
  signature: ^5.2.1
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.2

  #firebase_messaging: ^13.0.0
  firebase_remote_config: ^2.0.17
  dropdown_plus: ^0.0.9
  url_launcher: ^6.1.5
  get_storage: ^2.0.3
  # flutter_phone_state: ^0.5.9
  #sqflite: ^2.0.2+1
  flutter_multi_formatter: ^2.7.5
  awesome_notifications: ^0.6.21
  #connectivity: ^3.0.6
  connectivity_plus: ^2.3.7
  group_button: ^5.2.1
  badges: ^2.0.3
  flutter_image_compress: ^1.1.2
  #app_settings: ^4.1.8
  #audioplayers: ^0.20.1
  just_audio: ^0.9.29
  flutter_email_sender: ^5.1.0
  #flutter_screenutil: ^5.5.2
  #isar: ^2.5.0
  #isar_flutter_libs: 2.5.0 # contains the binaries
  #lottie: ^1.3.0
  web_socket_channel: ^2.2.0
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.10
  reorderables: ^0.5.0
  path_provider: ^2.0.11
  path: ^1.8.1
  #sqlite3: ^1.7.2
  undo: ^1.4.0
  upgrader: ^4.6.1
  flutter_native_splash: ^2.2.9
  #image_picker_ios: ^0.8.5+6
  disk_space: ^0.2.1
  percent_indicator: ^4.2.2
  #app_links: ^3.2.0

  #share_extend: ^2.0.0
  #google_ml_kit: ^0.12.0
  #camera: ^0.10.0
  #drift_dev: ^1.7.0
  #open_file: ^3.2.1
  #mobile_scanner: ^2.0.0
  #open_filex: ^4.1.1
  #install_referrer: ^1.2.1
  easy_app_installer: ^1.0.0
  shared_preferences: ^2.0.15
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: feature/scan-window
  #mlkit_scanner: ^0.3.2
  # mlkit_scanner:
  #   path: plugins/mlkit_scanner
  #barcode_finder: ^0.0.5
  #shimmer: ^2.0.0
  #socket_io_client: ^2.0.0
  #built_value: ^8.4.1

  #dropdown_search: ^4.0.1
  #call_log: ^3.2.3

  # rxdart: ^0.27.1
  # battery_info: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  #isar_generator: 2.5.0
  flutter_launcher_icons: '^0.10.0'

  build_runner: ^2.2.1
  #built_value_generator: ^8.1.1
  #build: ^2.3.0
  #moor_generator: ^4.6.0
  flutter_lints: ^2.0.1
  #build_web_compilers: ^3.2.3
  drift_dev: ^2.1.0
  flex_color_scheme: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/sound/
    - assets/fonts/
    #- assets/images/iel-logo.png
    #- assets/images/truck.png
    #- assets/images/icons8_cv.svg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
